[project]
name = "cipherdex"
version = "0.1.3"
description = "A CLI tool for encryption, decryption, and cryptanalysis of classical ciphers"
authors = [
    {name = "Varun"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer",
    "rich",
    "cryptography"
]

[project.scripts]
cipherdex = "cipherdex.main:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["cipherdex*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
